### ISSUE TITLE
从需要认证的私服下载无法正常下载

### ISSUE THREAD

**Issue by vicat47** [Ten-K/get-npm-tgz#19]

**Comment by Ten-K** [comment]
1. 请确保你的`npm`配置已拥有该私有仓库的权限
2. 能否提供详细的错误信息或者截图

**Comment by vicat47** [comment]
![image](https://github.com/Ten-K/get-npm-tgz/assets/19318221/73db67a8-b920-4cf6-b13a-cb28850b6b89)
下载下来的文件全部是空白

**Comment by Ten-K** [comment]
非常感谢您的反馈。
已确认该问题为`http请求`下载`tgz包`时无私有仓库权限导致。
平台目前暂不支持从需要认证的私服下载。

**Comment by Ten-K** [comment]
#20
