### ISSUE TITLE
首先工具很好用，感谢作者

### ISSUE THREAD

**Issue by liyunhan** [Ten-K/get-npm-tgz#38]
但是我使用的时候出现个问题，比如我npm i vue的时候，发现vue依赖的包都不存在，按理说我整个项目需要的应该都在node_modules里了，也应该记录在Package-lock.json了？我现在必须把缺少的包挨个下载上传才能正常Npm i

**Comment by Ten-K** [comment]
> 但是我使用的时候出现个问题，比如我npm i vue的时候，发现vue依赖的包都不存在，按理说我整个项目需要的应该都在node_modules里了，也应该记录在Package-lock.json了？我现在必须把缺少的包挨个下载上传才能正常Npm i

您好，我以`vue3.5.13`为例，下载的tgz是全量的，至于你说的npm i 时，依赖包缺失是否是您没有将tgz包全量上传至私服导致的

**Comment by liyunhan** [comment]
您好，问题已经解决了，包确实是全量下载的，您的工具没有任何问题。
一开始通过npm publish加脚本批量上传，个别带有scope的包无法正常上传被忽略了，后来通过api的方式解决。
感谢您的回复及开源这么便捷的工具。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 一万 ***@***.***&gt;
发送时间: 2024年12月25日 22:55
收件人: Ten-K/get-npm-tgz ***@***.***&gt;
抄送: liyunhan ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Ten-K/get-npm-tgz] 首先工具很好用，感谢作者 (Issue #38)





  
但是我使用的时候出现个问题，比如我npm i vue的时候，发现vue依赖的包都不存在，按理说我整个项目需要的应该都在node_modules里了，也应该记录在Package-lock.json了？我现在必须把缺少的包挨个下载上传才能正常Npm i
  
您好，我以vue3.5.13为例，下载的tgz是全量的，至于你说的npm i 时，依赖包缺失是否是您没有将tgz包全量上传至私服导致的

**Comment by Ten-K** [comment]
> 您好，问题已经解决了，包确实是全量下载的，您的工具没有任何问题。 一开始通过npm publish加脚本批量上传，个别带有scope的包无法正常上传被忽略了，后来通过api的方式解决。 感谢您的回复及开源这么便捷的工具。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 一万 ***@***.***&gt; 发送时间: 2024年12月25日 22:55 收件人: Ten-K/get-npm-tgz ***@***.***&gt; 抄送: liyunhan ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [Ten-K/get-npm-tgz] 首先工具很好用，感谢作者 (Issue #38) 但是我使用的时候出现个问题，比如我npm i vue的时候，发现vue依赖的包都不存在，按理说我整个项目需要的应该都在node_modules里了，也应该记录在Package-lock.json了？我现在必须把缺少的包挨个下载上传才能正常Npm i 您好，我以vue3.5.13为例，下载的tgz是全量的，至于你说的npm i 时，依赖包缺失是否是您没有将tgz包全量上传至私服导致的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

很高兴能帮助到您，祝生活愉快☺️
